# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'sigala.ui'
#
# Created: Fri Jul  9 09:09:10 2010
#      by: PyQt4 UI code generator 4.4.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

class Ui_SGuiProfe(object):
    def setupUi(self, SGuiProfe):
        SGuiProfe.setObjectName("SGuiProfe")
        SGuiProfe.resize(333, 523)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/img/cigala.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        SGuiProfe.setWindowIcon(icon)
        self.centralwidget = QtGui.QWidget(SGuiProfe)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.centralwidget)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.tGrupo = QtGui.QLineEdit(self.centralwidget)
        self.tGrupo.setObjectName("tGrupo")
        self.horizontalLayout_2.addWidget(self.tGrupo)
        self.bGrupoAction = QtGui.QPushButton(self.centralwidget)
        self.bGrupoAction.setCheckable(True)
        self.bGrupoAction.setDefault(True)
        self.bGrupoAction.setObjectName("bGrupoAction")
        self.horizontalLayout_2.addWidget(self.bGrupoAction)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.bViewResources = QtGui.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setUnderline(True)
        self.bViewResources.setFont(font)
        self.bViewResources.setCursor(QtCore.Qt.PointingHandCursor)
        self.bViewResources.setFocusPolicy(QtCore.Qt.NoFocus)
        self.bViewResources.setFlat(True)
        self.bViewResources.setObjectName("bViewResources")
        self.verticalLayout_2.addWidget(self.bViewResources)
        self.line = QtGui.QFrame(self.centralwidget)
        self.line.setFrameShape(QtGui.QFrame.HLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout_2.addWidget(self.line)
        self.lGrupo = QtGui.QLabel(self.centralwidget)
        self.lGrupo.setStyleSheet("""font: 75 14pt \"Bitstream Vera Sans\";
border-color: rgb(255, 0, 0);
""")
        self.lGrupo.setTextFormat(QtCore.Qt.RichText)
        self.lGrupo.setAlignment(QtCore.Qt.AlignCenter)
        self.lGrupo.setObjectName("lGrupo")
        self.verticalLayout_2.addWidget(self.lGrupo)
        self.line_2 = QtGui.QFrame(self.centralwidget)
        self.line_2.setFrameShape(QtGui.QFrame.HLine)
        self.line_2.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.verticalLayout_2.addWidget(self.line_2)
        self.tabWidget = QtGui.QTabWidget(self.centralwidget)
        self.tabWidget.setEnabled(False)
        self.tabWidget.setObjectName("tabWidget")
        self.tabGrupo = QtGui.QWidget()
        self.tabGrupo.setObjectName("tabGrupo")
        self.gridLayout = QtGui.QGridLayout(self.tabGrupo)
        self.gridLayout.setObjectName("gridLayout")
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.userList = QtGui.QListWidget(self.tabGrupo)
        self.userList.setAlternatingRowColors(True)
        self.userList.setSelectionMode(QtGui.QAbstractItemView.ExtendedSelection)
        self.userList.setSpacing(3)
        self.userList.setObjectName("userList")
        self.verticalLayout.addWidget(self.userList)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.bKick = QtGui.QPushButton(self.tabGrupo)
        self.bKick.setObjectName("bKick")
        self.horizontalLayout.addWidget(self.bKick)
        self.bBan = QtGui.QPushButton(self.tabGrupo)
        self.bBan.setObjectName("bBan")
        self.horizontalLayout.addWidget(self.bBan)
        self.bIdent = QtGui.QPushButton(self.tabGrupo)
        self.bIdent.setObjectName("bIdent")
        self.horizontalLayout.addWidget(self.bIdent)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.gridLayout.addLayout(self.verticalLayout, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tabGrupo, "")
        self.tabBan = QtGui.QWidget()
        self.tabBan.setObjectName("tabBan")
        self.gridLayout_2 = QtGui.QGridLayout(self.tabBan)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.verticalLayout_3 = QtGui.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.banList = QtGui.QListWidget(self.tabBan)
        self.banList.setAlternatingRowColors(True)
        self.banList.setSelectionMode(QtGui.QAbstractItemView.ExtendedSelection)
        self.banList.setSpacing(3)
        self.banList.setObjectName("banList")
        self.verticalLayout_3.addWidget(self.banList)
        self.bUnBan = QtGui.QPushButton(self.tabBan)
        self.bUnBan.setObjectName("bUnBan")
        self.verticalLayout_3.addWidget(self.bUnBan)
        self.gridLayout_2.addLayout(self.verticalLayout_3, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tabBan, "")
        self.verticalLayout_2.addWidget(self.tabWidget)
        self.bAbrirCerrarGrupo = QtGui.QPushButton(self.centralwidget)
        self.bAbrirCerrarGrupo.setEnabled(False)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/img/key.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        icon1.addPixmap(QtGui.QPixmap(":/img/key-forbidden.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.bAbrirCerrarGrupo.setIcon(icon1)
        self.bAbrirCerrarGrupo.setCheckable(True)
        self.bAbrirCerrarGrupo.setObjectName("bAbrirCerrarGrupo")
        self.verticalLayout_2.addWidget(self.bAbrirCerrarGrupo)
        SGuiProfe.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(SGuiProfe)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 333, 22))
        self.menubar.setObjectName("menubar")
        self.menuAcciones = QtGui.QMenu(self.menubar)
        self.menuAcciones.setObjectName("menuAcciones")
        self.menuAplicaciones = QtGui.QMenu(self.menubar)
        self.menuAplicaciones.setObjectName("menuAplicaciones")
        self.menuAy_uda = QtGui.QMenu(self.menubar)
        self.menuAy_uda.setObjectName("menuAy_uda")
        self.menuHerramientas = QtGui.QMenu(self.menubar)
        self.menuHerramientas.setObjectName("menuHerramientas")
        SGuiProfe.setMenuBar(self.menubar)
        self.statusBar = QtGui.QStatusBar(SGuiProfe)
        self.statusBar.setObjectName("statusBar")
        SGuiProfe.setStatusBar(self.statusBar)
        self.action_Salir = QtGui.QAction(SGuiProfe)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/img/exit.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_Salir.setIcon(icon2)
        self.action_Salir.setObjectName("action_Salir")
        self.actionAcerca_de = QtGui.QAction(SGuiProfe)
        self.actionAcerca_de.setObjectName("actionAcerca_de")
        self.actionAyuda = QtGui.QAction(SGuiProfe)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/img/help-faq.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionAyuda.setIcon(icon3)
        self.actionAyuda.setObjectName("actionAyuda")
        self.actionAcercaDe = QtGui.QAction(SGuiProfe)
        self.actionAcercaDe.setIcon(icon)
        self.actionAcercaDe.setObjectName("actionAcercaDe")
        self.actionLog = QtGui.QAction(SGuiProfe)
        self.actionLog.setObjectName("actionLog")
        self.menuAcciones.addAction(self.action_Salir)
        self.menuAy_uda.addAction(self.actionAyuda)
        self.menuAy_uda.addSeparator()
        self.menuAy_uda.addAction(self.actionAcercaDe)
        self.menuHerramientas.addAction(self.actionLog)
        self.menubar.addAction(self.menuAcciones.menuAction())
        self.menubar.addAction(self.menuAplicaciones.menuAction())
        self.menubar.addAction(self.menuHerramientas.menuAction())
        self.menubar.addAction(self.menuAy_uda.menuAction())

        self.retranslateUi(SGuiProfe)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QObject.connect(self.action_Salir, QtCore.SIGNAL("activated()"), SGuiProfe.close)
        QtCore.QObject.connect(self.tGrupo, QtCore.SIGNAL("returnPressed()"), self.bGrupoAction.click)
        QtCore.QMetaObject.connectSlotsByName(SGuiProfe)

    def retranslateUi(self, SGuiProfe):
        SGuiProfe.setWindowTitle(QtGui.QApplication.translate("SGuiProfe", "SIGALA", None, QtGui.QApplication.UnicodeUTF8))
        self.tGrupo.setToolTip(QtGui.QApplication.translate("SGuiProfe", "Escriba aquí el nombre del grupo que desea crear", None, QtGui.QApplication.UnicodeUTF8))
        self.bGrupoAction.setToolTip(QtGui.QApplication.translate("SGuiProfe", "Crea un grupo de trabajo con el nombre especificado", None, QtGui.QApplication.UnicodeUTF8))
        self.bGrupoAction.setText(QtGui.QApplication.translate("SGuiProfe", "Crear grupo", None, QtGui.QApplication.UnicodeUTF8))
        self.bViewResources.setStyleSheet(QtGui.QApplication.translate("SGuiProfe", "color: #373891;", None, QtGui.QApplication.UnicodeUTF8))
        self.bViewResources.setText(QtGui.QApplication.translate("SGuiProfe", "Ver grupos existentes en la red", None, QtGui.QApplication.UnicodeUTF8))
        self.lGrupo.setToolTip(QtGui.QApplication.translate("SGuiProfe", "Nombre del grupo actual", None, QtGui.QApplication.UnicodeUTF8))
        self.userList.setToolTip(QtGui.QApplication.translate("SGuiProfe", "Lista de usuarios que forman parte del grupo de trabajo", None, QtGui.QApplication.UnicodeUTF8))
        self.bKick.setToolTip(QtGui.QApplication.translate("SGuiProfe", "Expulsa a un usuario del grupo", None, QtGui.QApplication.UnicodeUTF8))
        self.bKick.setText(QtGui.QApplication.translate("SGuiProfe", "Expulsar", None, QtGui.QApplication.UnicodeUTF8))
        self.bBan.setToolTip(QtGui.QApplication.translate("SGuiProfe", "Prohibe al usuario el acceso al grupo", None, QtGui.QApplication.UnicodeUTF8))
        self.bBan.setText(QtGui.QApplication.translate("SGuiProfe", "Prohibir acceso", None, QtGui.QApplication.UnicodeUTF8))
        self.bIdent.setToolTip(QtGui.QApplication.translate("SGuiProfe", "Identifica al usuario", None, QtGui.QApplication.UnicodeUTF8))
        self.bIdent.setText(QtGui.QApplication.translate("SGuiProfe", "Identificar", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabGrupo), QtGui.QApplication.translate("SGuiProfe", "En el grupo", None, QtGui.QApplication.UnicodeUTF8))
        self.banList.setToolTip(QtGui.QApplication.translate("SGuiProfe", "Lista de usuarios que han sido expulsados del grupo de trabajo", None, QtGui.QApplication.UnicodeUTF8))
        self.bUnBan.setToolTip(QtGui.QApplication.translate("SGuiProfe", "Readmite un usuario al que se le ha prohibido la entrada", None, QtGui.QApplication.UnicodeUTF8))
        self.bUnBan.setText(QtGui.QApplication.translate("SGuiProfe", "Readmitir", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabBan), QtGui.QApplication.translate("SGuiProfe", "Acceso prohibido", None, QtGui.QApplication.UnicodeUTF8))
        self.bAbrirCerrarGrupo.setToolTip(QtGui.QApplication.translate("SGuiProfe", "Permite o deniega el acceso al grupo de trabajo", None, QtGui.QApplication.UnicodeUTF8))
        self.bAbrirCerrarGrupo.setText(QtGui.QApplication.translate("SGuiProfe", "Cerrar grupo", None, QtGui.QApplication.UnicodeUTF8))
        self.menuAcciones.setTitle(QtGui.QApplication.translate("SGuiProfe", "&Acciones", None, QtGui.QApplication.UnicodeUTF8))
        self.menuAplicaciones.setTitle(QtGui.QApplication.translate("SGuiProfe", "A&plicaciones", None, QtGui.QApplication.UnicodeUTF8))
        self.menuAy_uda.setTitle(QtGui.QApplication.translate("SGuiProfe", "Ay&uda", None, QtGui.QApplication.UnicodeUTF8))
        self.menuHerramientas.setTitle(QtGui.QApplication.translate("SGuiProfe", "Herramientas", None, QtGui.QApplication.UnicodeUTF8))
        self.action_Salir.setText(QtGui.QApplication.translate("SGuiProfe", "&Salir", None, QtGui.QApplication.UnicodeUTF8))
        self.action_Salir.setShortcut(QtGui.QApplication.translate("SGuiProfe", "Ctrl+Q", None, QtGui.QApplication.UnicodeUTF8))
        self.actionAcerca_de.setText(QtGui.QApplication.translate("SGuiProfe", "Acerca &de", None, QtGui.QApplication.UnicodeUTF8))
        self.actionAyuda.setText(QtGui.QApplication.translate("SGuiProfe", "Ayuda", None, QtGui.QApplication.UnicodeUTF8))
        self.actionAcercaDe.setText(QtGui.QApplication.translate("SGuiProfe", "Acerca &de...", None, QtGui.QApplication.UnicodeUTF8))
        self.actionLog.setText(QtGui.QApplication.translate("SGuiProfe", "Visor de eventos", None, QtGui.QApplication.UnicodeUTF8))


if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    SGuiProfe = QtGui.QMainWindow()
    ui = Ui_SGuiProfe()
    ui.setupUi(SGuiProfe)
    SGuiProfe.show()
    sys.exit(app.exec_())

